/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/awesome-button/awesome-button";
export namespace Components {
    interface AwesomeButton {
        "variant": ButtonVariant;
    }
}
declare global {
    interface HTMLAwesomeButtonElement extends Components.AwesomeButton, HTMLStencilElement {
    }
    var HTMLAwesomeButtonElement: {
        prototype: HTMLAwesomeButtonElement;
        new (): HTMLAwesomeButtonElement;
    };
    interface HTMLElementTagNameMap {
        "awesome-button": HTMLAwesomeButtonElement;
    }
}
declare namespace LocalJSX {
    interface AwesomeButton {
        "variant"?: ButtonVariant;
    }
    interface IntrinsicElements {
        "awesome-button": AwesomeButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "awesome-button": LocalJSX.AwesomeButton & JSXBase.HTMLAttributes<HTMLAwesomeButtonElement>;
        }
    }
}
